- name: Check if College Board Secure Browser is installed
  command: dpkg-query -W "cbsecurebrowser"
  register: secure_browser_check_deb
  failed_when: secure_browser_check_deb.rc > 1
  changed_when: secure_browser_check_deb.rc == 1

- name: Download College Board Secure Browser
  ansible.builtin.get_url:
    url: https://secure-media.collegeboard.org/digitalServices/digital-testing/files/CBSecureBrowser15.0-2022-08-08.deb
    dest: /home/ansible/CBSecureBrowser.deb
  when: secure_browser_check_deb.rc == 1

- name: Install College Board Secure Browser
  apt: deb="/home/ansible/CBSecureBrowser.deb"
  when: secure_browser_check_deb.rc == 1

- name: Creating CollegeBoard Secure Browser Desktop Icon
  copy:
    dest: "/home/tkastudent/Desktop/cbsecurebrowser.desktop"
    content: |
      #!/usr/bin/env xdg-open
      [Desktop Entry]
      Encoding=UTF-8
      Version=8.0
      Type=Application
      Terminal=false
      Exec=/usr/lib/CBSecureBrowser/CBSecureBrowser
      Icon=/usr/lib/CBSecureBrowser/securebrowser.png
      Name=CollegeBoardSecureBrowser
      Comment=College Board Secure Browser
      GenericName=College Board Secure Web Browser
      Keywords=Internet;WWW;Browser;Web;Explorer
      Categories=GNOME;GTK;Network;WebBrowser

- name: Change Shortcut Mode and Ownership
  file:
    path: /home/tkastudent/Desktop/cbsecurebrowser.desktop
    owner: tkastudent
    group: tkastudent
    mode: 0755
