- name: Check if Indiana Secure Browser is installed
  command: dpkg-query -W "indianasecurebrowser"
  register: secure_browser_check_deb
  failed_when: secure_browser_check_deb.rc > 1
  changed_when: secure_browser_check_deb.rc == 1

- name: Download Indiana Secure Browser
  ansible.builtin.get_url:
    url: https://sb.portal.cambiumast.com/geturls?clientName=indiana&operatingSystem=ubuntu
    dest: /home/ansible/IndianaSecureBrowser.deb
  when: secure_browser_check_deb.rc == 1

- name: Install Indiana Secure Browser
  apt: deb="/home/ansible/IndianaSecureBrowser.deb"
  when: secure_browser_check_deb.rc == 1

- name: Creating Indiana Secure Browser Desktop Icon
  copy:
    dest: "/home/tkastudent/Desktop/indianasecurebrowser.desktop"
    content: |
      #!/usr/bin/env xdg-open
      [Desktop Entry]
      Encoding=UTF-8
      Version=8.0
      Type=Application
      Terminal=false
      Exec=/usr/lib/IndianaSecureBrowser/IndianaSecureBrowser
      Icon=/usr/lib/IndianaSecureBrowser/securebrowser.png
      Name=IndianaSecureBrowser
      Comment=Indiana Secure Browser
      GenericName=Indiana Secure Web Browser
      Keywords=Internet;WWW;Browser;Web;Explorer
      Categories=GNOME;GTK;Network;WebBrowser

- name: Change Shortcut Mode and Ownership
  file:
    path: /home/tkastudent/Desktop/indianasecurebrowser.desktop
    owner: tkastudent
    group: tkastudent
    mode: 0755
